### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by bferguson3** [max1220/lua-getch#1]
Just a thanks for making this.
Do you mind updating the readme.md for proper usage? I had to copy your example to get it to work right.
Otherwise, excellent work - it shocks me how many people push to use ncurses when it's just an x11 or glfw implementation with a ton of overhead.

**Comment by max1220** [comment]
I just updated the README.md, it was outdated and incomplete. I also restructured my code a little, added a make install target, added more examples and fixed a bug(pushing the result twice in l_getch_non_blocking). They are currently on the wip branch, but I'll merge it into the master branch when I have tested my changes.

And thank you for your kind feedback - I'm just glad someone can get some use out of this :P

**Comment by max1220** [comment]
I have merged the updated library into the master branch. I will close this issue now.
