### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by vredesbyyrd** [max1220/lua-getch#2]
First, thank you for sharing this. Its very useful and nice not to have to install some larger libraries. Second, I have a fairly general help question that I think `getch` + `lua-time` can help me solve. If you do not want to tackle _my_ issue I totally understand, feel free to close!  To the problem...

I am working on a simple database search tool, and am stuck trying to figure out how to add a debounce routine to the input entry so that every "keypress" does not call my search function, rather, the search function will only be called after the user stops typing for 500ms.

I am using  [rofi blocks](https://github.com/OmarCastro/rofi-blocks) as the "gui". Its a `C` program that reads the output of scripts to create menus. Rofi-blocks does most of the heavy lifting here...

> The module works by reading the stdin line by line to update rofi content. It can execute an application in the background (lua program I am working on), which will be used to communicate with the module. The communication is made using file descriptors. The module reads the output of the background program and writes events its input.

Currently every keypress calls the function (`ParseView`) that updates the search results. This is inefficient. To resolve this the end goal is to add a small timeout so that the search function only gets called once the _user stops typing_.

This is the current (and stripped down) implementation without any timeout/debounce.

`G_MESSAGES_DEBUG=Dialogs.BlocksMode rofi -modi blocks -show blocks -blocks-wrap '/path/to/script/test.lua'`

```lua

#!/usr/bin/lua

package.cpath = package.cpath .. ";../?.so"
local getch = require("lua-getch")
local time = require("time")
local json = require('cjson')

BUF = { name=nil, value=nil, data=nil}

function ParseView(arg)
  local t = {
	["input action"] = 'send',
	["lines"] 	     = arg.lines
  }

  local rofi_input = json.encode(t)

  io.stdout:setvbuf('line')
  io.stdout:write(rofi_input .. '\n')

  local rofi_output = json.decode( io.stdin:read('*l') )

  BUF['name']  = rofi_output.name
  BUF['value'] = rofi_output.value -- what user types
  BUF['data']  = rofi_output.data
end

repeat
  if BUF['value'] ~= '' then
     --currently displays what user types, normally will call fts5 table with 'BUF['value']' as search term
    ParseView{lines={ {text=BUF['value']} }}
  else
    ParseView{lines={ {text='waiting for input'} }}
  end
until BUF['name'] == 'select entry' -- when user selects row from list of results
```

I know this weird program can be hard to decipher whats going on, so here is a link to my onedrive with two videos that may make it more clear. `sample_input.mkv` is the more relevant example. The terminal is showing program debug output, rofi is screen left.  [onedrive](https://1drv.ms/u/s!Au0J8kZrcsZnjMIOJf34iVHAOe6llw?e=Smhtel)

If you have not noticed I am still very much learning lua :) Do you think with `getch` + `lua-time` it would be possible to implement a timeout, so `ParseView` is only called after the user stops typing a query? I tried this rather hackish approach... but it is predictably not working. My guess is the implementation would have to be completely different. 

If you do not mind giving me any hints on how you would go about implementing a debounce routine it would be greatly appreciated. Hate to admit it, but i've been stuck for 2 days.   

```
local on_start = ParseView{lines={ {text='waiting for input'} }}
local timeout = 0.5
repeat
  local start = time.monotonic()
  local c,err = getch.non_blocking(timeout)
  local dt = time.monotonic() - start

  if dt > timeout  then
    ParseView{lines={ {text=BUF['value']} }}
  end
until BUF['name'] == 'select entry'
```

**Comment by max1220** [comment]
I'm always glad to help, if I can ;)

From what I understand rofi kind of takes the role of a terminal emulator(in that it can launch a program in it, and that program can feed it user input via stdin, and generate graphical output by writing commands to stdout)
Is that correct? I haven't used that software.

The code snippet below has a few issues.
First, getch.non_blocking reads(consumes!) a character of the JSON input stream, but doesn't append it to the rest of the data from the input stream before JSON parsing. This will most likely cause JSON parsing errors, as the first character is always missing.

Second, measuring the delta-time for the getch.non-blocking calls is most likely not what you want, because that means when typing a sequence no search is made until the entire sequence has completed(every call has small dt). Ideally, you can see results as you type, up to 0.5 times per second("rate limit").

Here's an untested and reworked version of your first script that uses such a rate limit:

```
#!/usr/bin/env lua5.1
local time = require("time")
local getch = require("getch")
local json = require("cjson")

-- updates the list of items in the rofi menu
local function update_output(lines)
        io.stdout:write(json.encode({
                ["input action"] = "send",
                ["lines"] = lines
        }))
        io.stdout:flush()
        return true
end

-- rate limit calls to a function.
-- (returns a function that can be called once every rate seconds)
local function rate_limit(f, rate)
        local last = 0 -- last time this function was called
        return function(...)
                local now = time.monotonic()
                if (now-last) > rate then -- function is ready to be called
                        last = now
                        return f(...)
                end
        end
end

-- initial update of the list
update_output()

-- maximum time between updates
local timeout = 0.5

-- create a rate-limited function, so that update_output can be called up to every 0.5 seconds
local update_output_slow = rate_limit(update_output, timeout)

-- holds last input from rofi
local BUF = { name=nil, value=nil, data=nil }

repeat
        -- read a single character from stdin
        local ch,err = getch.non_blocking(timeout)
        if ch then
                -- handle the input from rofi
                local input = json.decode(string.char(ch) .. io.read("*l"))
                BUF.name = input.name
                BUF.value = input.value
                BUF.data = input.data
        end

        -- send updated list to rofi(update output)
        update_output_slow()
        -- Calling update_output_slow only when the list changed is left as an exercise for the reader :P
until BUF["name"] == "select entry"
```
Keep in mind that maybe you could even get by without the lua-getch library:
If the database lookup is what takes too long, you could easily wrap the function for getting data from the database in the rate_limit function, and just use the last found values when assembling the menu.
Then you don't need the lua-getch library, because you can just always send the complete menu(containing information that is *up to* 0.5 seconds of typing out of date). Have you tested if it's fast enough without a database binding(Just the GUI code)?

Also keep in mind that lua-getch was made for interactive terminal input, not reading binary data!
Maybe I'll add wait functionality that doesn't mess with the terminal to lua-getch in the future.
You could also use something more complete like luaPosix, using select etc., or implement it like a C application using the amazing LuaJIT FFI.
I hope I could help, feel free to ask more questions, kind regards :)

**Comment by vredesbyyrd** [comment]
> From what I understand rofi kind of takes the role of a terminal emulator(in that it can launch a program in it, and that program can feed it user input via stdin, and generate graphical output by writing commands to stdout)
> Is that correct? I haven't used that software.

That is correct.

I very much appreciate the detailed walk-through.  I had a little time to play with it right now, and with your help I was able to get the wanted behavior :) 

I still have to implement it into the existing code base which I will do tomorrow. I'll report back than. 

Thanks again!

**Comment by max1220** [comment]
Always glad to help :)
Let me know when your implementation works fully(so I can close the issue), or if you have any further questions :P

**Comment by vredesbyyrd** [comment]
> Second, measuring the delta-time for the getch.non-blocking calls is most likely not what you want, because that means when typing a sequence no search is made until the entire sequence has completed(every call has small dt). Ideally, you can see results as you type, up to 0.5 times per second("rate limit").

So for one of the scripts I am working on I will probably use rate-limiting. For the other(s) I am sticking with the behavior i initially described. I could see the rate-limiting function/wrapper coming in very handy in certain situations though. I have a web-scraping / search tool I plan on making next, so that could come in useful. Thank you :) Also, I should point out I still struggle working with time, generally....lol, thats how novice I am. Most of the the programming I have done up until now is just automating tasks. I'm using this current project and some others as means to learn. Most of the stuff I have done is in python, lua, bash etc and a few very small terminal programs in C. But I like the small, batteries not included nature of lua and want to learn it thorouly until I move onto something else. Anyway...

For now, the general function I am using looks like this....


```lua
local timeout = 0.5
local last_query = nil
repeat
    local start = socket.gettime()
    local ch, err = getch.non_blocking(timeout)
    if ch then
        -- handle the input from rofi
        local input = json.decode(string.char(ch) .. io.stdin:read("*l"))
        BUF.name = input.name
        BUF.value = input.value
        BUF.data = input.data
    end

    --if new query received send updated list to rofi(update output)
    local query = BUF.value
    if not ch and query ~= last_query then
        last_query = query
        update_output()
    end
until BUF["name"] == "select entry"
```

> The code snippet below has a few issues.
> First, getch.non_blocking reads(consumes!) a character of the JSON input stream, but doesn't append it to the rest of the data from the input stream before JSON parsing. This will most likely cause JSON parsing errors, as the first character is always missing. 

So as you predicted, I run into JSON decode errors with one of the scripts on at least 75% of the queries (music script). But rather interestingly with the other (movies / tv) script I have not been able to trigger a single JSON decode error. Both use the exact same code, above, implemented in the same manner. The music script is quite a bit larger with more functionality, but ultimately the way they make queries to the fts5 sqlite table is the same. Oddly, I can make specific queries without issue eg. `ulrich schnauss` never fails. But `fka twigs` fails after the `space` char every time.  

_Rofi debug output_ 

```
(process:34739): BlocksMode-DEBUG: 21:02:45.910: on_render.active line 0
(process:34739): BlocksMode-DEBUG: 21:02:46.922: blocks_mode_preprocess_input
(process:34739): BlocksMode-DEBUG: 21:02:46.922: sending event: {"name":"input change", "value":"f", "data":""}
(process:34739): BlocksMode-DEBUG: 21:02:46.933: calling on_render
(process:34739): BlocksMode-DEBUG: 21:02:46.933: on_render.selected line 0
(process:34739): BlocksMode-DEBUG: 21:02:46.933: on_render.next pos 1
(process:34739): BlocksMode-DEBUG: 21:02:46.933: on_render.active line 0
(process:34739): BlocksMode-DEBUG: 21:02:47.078: blocks_mode_preprocess_input
(process:34739): BlocksMode-DEBUG: 21:02:47.078: sending event: {"name":"input change", "value":"fk", "data":""}
(process:34739): BlocksMode-DEBUG: 21:02:47.081: calling on_render
(process:34739): BlocksMode-DEBUG: 21:02:47.081: on_render.selected line 0
(process:34739): BlocksMode-DEBUG: 21:02:47.081: on_render.next pos 1
(process:34739): BlocksMode-DEBUG: 21:02:47.081: on_render.active line 0
(process:34739): BlocksMode-DEBUG: 21:02:47.201: blocks_mode_preprocess_input
(process:34739): BlocksMode-DEBUG: 21:02:47.201: sending event: {"name":"input change", "value":"fka", "data":""}
(process:34739): BlocksMode-DEBUG: 21:02:47.204: calling on_render
(process:34739): BlocksMode-DEBUG: 21:02:47.204: on_render.selected line 0
(process:34739): BlocksMode-DEBUG: 21:02:47.204: on_render.next pos 1
(process:34739): BlocksMode-DEBUG: 21:02:47.204: on_render.active line 0
(process:34739): BlocksMode-DEBUG: 21:02:47.385: blocks_mode_preprocess_input
(process:34739): BlocksMode-DEBUG: 21:02:47.385: sending event: {"name":"input change", "value":"fka ", "data":""}
/usr/bin/lua: /home/clu/scripts/rofi_music/mpd-block-modi.lua:331: Expected object key string but found T_OBJ_BEGIN at character 2
stack traceback:
	[C]: in function 'cjson.decode'
        /home/clu/scripts/rofi_music/mpd-block-modi.lua:331: in function 'update_output'
	/home/clu/scripts/rofi_music/mpd-block-modi.lua:172: in local 'Main'
	/home/clu/scripts/rofi_music/mpd-block-modi.lua:1059: in main chunk
```

My guess is there is no way around this, otherwise you would not have predicted it, haha. I tried a few different JSON parsers to be sure, but they all choke in the same manner. I assume because... 

> ...but doesn't append it to the rest of the data from the input stream before JSON parsing

> Also keep in mind that lua-getch was made for interactive terminal input, not reading binary data!
Maybe I'll add wait functionality that doesn't mess with the terminal to lua-getch in the future.
You could also use something more complete like luaPosix, using select etc., or implement it like a C application using the amazing LuaJIT FFI.
I hope I could help, feel free to ask more questions, kind regards :)

Noted :)  I may look into using `luaPosix` or perhaps `lua Socket` and its `select` function. I do not mind using `getch` as a dependency at all, its a neat little module. But if I cannot fix the JSON parsing issue maybe I'll have to go one of those routes :/

If you have anymore thoughts / advice on resolving or working around the JSON decode issue I am all ears. I'll take a look at your previous recommendations tomorrow with a fresh brain...getting late here :) 

Thanks again for your time and help!!!

EDIT: 

>Have you tested if it's fast enough without a database binding(Just the GUI code)? 

If I am understanding your question correctly, have I tried using rofis built in filtering to filter the list as opposed to querying the sqlite db directly? I'm using both methods actually. For the music program, you can browse by different catagories eg `artist, albums, genres, recent, mixtape, acousticbrainz, queue`, which can than be filtered using rofi's built in filter (similar to fzf). In addition, there is a "global" search mode (this issue) that allows for more complex "full text search"  queries.  Rofi's filtering is fast enough, just not specific enough for what I am trying to do, if that makes sense.

**Comment by vredesbyyrd** [comment]
**EDIT** for clarity:  I somehow overlooked something very obvious (and not smart) in how I implemented this. Although each 'keypress' was not writing to `stdout`, it was still returing `QueryFts()` on each keystroke, which could explain why adding `limit` to the query helped .. :-1:  Fixing that almost nullifies the below issue. JSON parsing errors happen maaybe 1/50 times (without the limit). In real use I never make 50 consecutive queries. So for now I will just catch the sort-of infrequent JSON error using `require("cjson.safe").decode`  so the program does not crash.  

Although I still intend to look into creating a basic `C` module so the errors don't occur in the first place. 

_Original message:_



One last thing that perplexes me... 

If I add a limit to the rows returned by sqlite it behaves well 90%+ of the time. I cant see how that would have an effect on the json parsing of the search query.  

```lua
local function QueryFts(str)

  local stmt = db:prepare([[
	SELECT title, mixtape, year, albumartist, album, album_id, id
	FROM beets
	WHERE beets match ?||'*'
	ORDER BY id
      LIMIT 1000 -- why does limit "mask" this problem.
  ]])

  -- returns formatted search results, [str] is search term
  local res = TracksFormat(str, stmt)

  --[[ we do not want to pass an empty
  table to UpdateView. If query returns
  no matches text = 'no results' ]]
  local next = next
  if next(res) == nil then
	local res = {'no results'}
	return res
  else
	return res
  end
end
```

I think my best bet might be trying to make a small `C` module more geared toward this specific use case. Doing so could also be a good way to fully wrap my head around the problem. 

I'll close this issue as its becoming out of `lua-getch` scope. Thanks again for the lessons.
