### ISSUE TITLE
Release on luarocks.org

### ISSUE THREAD

**Issue by E-Fir** [max1220/lua-getch#5]
Hi!
Please release your nice library on luarocks.org .
Thank you in advance.

**Comment by agladysh** [comment]
Hi! We would really like a luarocks.org release, to comply with our internal policy of using only released code.

Please tell me if we can help in any way.

**Comment by max1220** [comment]
For your convenience, I've uploaded this to the official LuaRocks repository:
https://luarocks.org/modules/max1220/lua-getch
This is my first properly published LuaRocks module, let me know what you think!
You can now install this library using:
```
luarocks install lua-getch
```

(Ignore the 0.0-3 verison; It's missing the bit32 dependency declaration)

**Comment by E-Fir** [comment]
@max1220 Looks good for me. Thank you very much!
